# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Set variables once
variables:
  project_token: 248811095536630189226569748169524069011398990388018621921
  test_run_id: 285059


steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: sudo apt-get update
- script: sudo apt-get install -y openjfx
- script: sudo apt-get install -y ruby-dev
- script: sudo apt-get install zlib1g-dev
- script: mvn clean install
- script: gem install hiptest-publisher
- script: hiptest-publisher -c cucumber-java.conf --token=$(project_token) --only=features,step_definitions
  displayName: 'Update the tests'
- script: hiptest-publisher -c cucumber-java.conf --token=$(project_token) --show-actionwords-diff-as-json
  displayName: 'Check if actionwords have been created, updated or deleted'
- script: hiptest-publisher -c cucumber-java.conf --token=$(project_token) --test-run-id=$(test_run_id) --without=actionwords
  displayName: 'Install hiptest-publisher and fetch UIDs in each scenario included in your test run'
- script: mvn test 
  displayName: 'Build tests'
- script: hiptest-publisher -c cucumber-java.conf --token=$(project_token) -p "target/cuke-results.json" --test-run-id=$(test_run_id)
  displayName: 'Push the test results file to HipTest'