# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      
      - run:
        name: install hiptest-publisher docker image as an executable file
        command: |
          echo "#! /bin/bash" >  ~/repo/hiptest-publisher
          echo "docker run --rm --volume=\"$(pwd):/app\" hiptest/hiptest-publisher  \"\$@\"" >> ~/repo/hiptest-publisher
          sudo chmod +x ~/repo/hiptest-publisher 
      - store_artifacts:
          path: ~/repo/hiptest-publisher
          destination: artifact-file
          
     
      - run:
          name: Update tests
          command:
            ./hiptest-publisher --token=${SECRET_TOKEN} -c cucumber-java.conf --only=features,step_definitions
      
      - run:
          name: regenerate tests and fetch UIDs
          command:
            ./hiptest-publisher --token=${SECRET_TOKEN} -c cucumber.conf --test-run-id=${TEST_RUN_ID} --without=actionwords

      # run tests!
      - run:
          name: run tests
          command:
            mvn test
            
      - run:
          name: push test results file
          command:
            ./hiptest-publisher -c cucumber.conf --token=${SECRET_TOKEN} --push="target/cuke-results.json" --test-run-id=${TEST_RUN_ID} --push-format cucumber-json
